### PR TITLE
Eslint

### PR DESCRIPTION
**Pull request by adwydman**
Firstly I'm sorry for the commit names, I was testing if `pre-commit` works.

I am creating a pull request for final approval, as many things in the code are going to be changed.

### CODE REVIEW

**Comment by kuba-orlik** [comment]
The commit messages are... embarassing ;p. Please rebase the branch so they're squashed into one, or at least change their messages into something meaningful :)

Also, reviewing 1000+ changed is a daunting task. Is there a possibility you could divide the changes into separate commits, like "Add semicolons", "Change var to const" etc?

Thirdly, didn't we agree on not changing `var` -> `const`/`let` in old codebase for now?

**Comment by adwydman** [comment]
>Please rebase the branch so they're squashed into one, or at least change their messages into something meaningful :) 

Noted.

>Also, reviewing 1000+ changed is a daunting task. Is there a possibility you could divide the changes into separate commits, like "Add semicolons", "Change var to const" etc?

I'm not actually expecting anyone to review all of those changes, it's more about checking the ESLint config package to see if the rules there are sufficient.

>Thirdly, didn't we agree on not changing var -> const/let in old codebase for now?

We agreed that it won't be a dedicated task, but only when encountering `var` when working on the code.

**Comment by kuba-orlik** [comment]
The config looks OK to me :) Once you rebase the branch so there are no redundant and weirdly-named commits, I'll be willing to merge it :)

**Comment by adwydman** [comment]
@kuba-orlik I renamed the commit titles, but I am afraid I might have broken something...

**Comment by kuba-orlik** [comment]
Why do you think so?

**Comment by adwydman** [comment]
I never used `rebase`, so maybe that's why :)

**Comment by kuba-orlik** [comment]
Is the result of `npm test` different than before rebase?

**Comment by adwydman** [comment]
No, it's the same - 128 passing.

**Comment by kuba-orlik** [comment]
Then I think it's unlikely you broke something with the code. Will check the commit graph status

**Comment by adwydman** [comment]
I had to create a separate branch `eslint-temp`, because I effed up something. Nevertheless, ESLint is now on references!

**Pull request closed without merging**
