### PR TITLE
Improve field type text

### PR DESCRIPTION
**Pull request by arkadiusz-wieczorek**

### CODE REVIEW

**Comment by arkadiusz-wieczorek** [comment]
Broken test for user manager I've had from the beginning my work on field type text.

**Comment by arkadiusz-wieczorek** [comment]
I propose add second field-type-just-text or field-type-simple-text because we have problem e.g. with user manager and because test doesn't pass.

```js
var Sealious = require("sealious");
var user = new Sealious.ChipTypes.ResourceType({
	name: "user",
	fields: [{
		name: "username",
		type: "text",
		required: true
	}, {
		name: "email",
		type: "email"
	}, {
		name: "password",
		type: "text",
		required: true
	}, {
		name: "status",
		type: "text"
	}, ]
});
```

**Comment by kuba-orlik** [comment]
I suggest we solve that with the `.valueOf`trick :)

**Comment by arkadiusz-wieczorek** [comment]
yep. :)



*Best regards | Pozdrawiam,Arkadiusz Wieczorek*
JavaScript developer
co-founder of Placetag.pl
github.com/arkadiusz-wieczorek

**Comment by adwydman** [comment]
What is up with this pull request?

**Comment by kuba-orlik** [comment]
From our trello board I infer that this was tested, works and only waits for acceptance and a merge.

I think that the mission here was to sanitize the text by default. 

@adwydman if you have some time on your hands please look through this PR. I don't think it's a good idea to merge it to v0.6, and lose it in v0.7. So maybe it should be moved to v0.7?

**Comment by kuba-orlik** [comment]
From our trello board I infer that this was tested, works and only waits for acceptance and a merge.

I think that the mission here was to sanitize the text by default. 

@adwydman if you have some time on your hands please look through this PR. I don't think it's a good idea to merge it to v0.6, and lose it in v0.7. So maybe it should be moved to v0.7?

**Comment by adwydman** [comment]
I think it should be merged to `references`.

**Comment by adwydman** [comment]
Would you like me to do it now?

**Comment by kuba-orlik** [comment]
If you consider this branch to be functional and well-tested, please do merge it to `references`

**Comment by adwydman** [comment]
This branch was merged to `references`.

**Comment by kuba-orlik** [comment]
@adwydman would you consider updating the [User Reference](https://github.com/sealcode/sealious-user-reference) to reflect the change from this PR?

**Comment by adwydman** [comment]
But I don't see anything that should be update there.

**Comment by kuba-orlik** [comment]
[Field-type-text's storage format](https://github.com/sealcode/sealious-user-reference#text) surely needs updating

**Comment by adwydman** [comment]
I didn't implement the changes, so I don't really know what to update.

**Pull request closed without merging**
