### PR TITLE
Get rid of the 'accept, reject' interface

### PR DESCRIPTION
**Pull request by kuba-orlik**

### CODE REVIEW

**Comment by kuba-orlik** [comment]
I'll correct the coverage soon :)

**Comment by kuba-orlik** [comment]
@adwydman Coveralls [seems to be undergoing some server issues](https://github.com/lemurheavy/coveralls-public/issues/834), but as you can manually check I've raised the coverage to 46%. Please review and merge this branch :)

**Comment by adwydman** [comment]
I love how you created a separate function to test `is_proper_value` <3 I assume that the change is backwards compatible and doesn't right anything, right?

**Comment by kuba-orlik** [comment]
Yep, the `test_is_proper_value` method just calls `describe` and `it` as usual, no breaking changes here :)

**Comment by kuba-orlik** [comment]
When you decide to merge it, please remember to merge this thing as well: https://github.com/sealcode/sealious-user-reference/pull/1 :)

**Comment by adwydman** [comment]
Merged here and there. :)

**Pull request merged**
