### PR TITLE
Change 'ResouceType' to 'Collection'

### PR DESCRIPTION
**Pull request by kuba-orlik**
This is a breaking API change. Now you create what was previously known as a `ResourceType` like so:

```javascript
new Sealious.Collection({...declaration
```

Please note that this change required updating the [https://github.com/sealcode/sealious-integration-tests](integration-tests).  I've pushed the necessary changes to the integration tests into the `alpha` branch of it's repo.

### CODE REVIEW

**Comment by adwydman** [comment]
I think there were no tests for `ResourceType`, are you sure that this change doesn't break anything?

**Comment by kuba-orlik** [comment]
Integration tests pass! That means that the relations between the channels and collections are kept intact :)

**Comment by adwydman** [comment]
All right, merging.

**Comment by adwydman** [comment]
@kuba-orlik Remember to adjust the documentation and user guide. :)

**Comment by kuba-orlik** [comment]
https://github.com/sealcode/sealious-user-reference/pull/2 I've updated the user-reference :)

**Comment by kuba-orlik** [comment]
(please, review it)

**Pull request merged**
